name-template: '$NEXT_PATCH_VERSION-frontend'
tag-template: '$NEXT_PATCH_VERSION-frontend'
include-paths:
  - "scripts/"
  - "roles/frontend/"
categories:
  - title: 🚀 Features
    labels:
      - 'feature'
      - 'enhancement'
  - title: 🐛 Bug Fixes
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 🧰 Maintenance
    labels:
      - chore
autolabeler:
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
  - label: 'bug'
    branch:
      - '/^(bug|fix)+\/.+/'
replacers:
  - search: '/([A-Z][A-Z0-9]{2,}-\d+)/g'
    replace: '[$1](https://diligentbrands.atlassian.net/browse/$1)'
exclude-labels:
  - 'skip-changelog'
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## What’s Changed
  
  $CHANGES
