name: learn-github-actions
on: pull_request
jobs:
  check-bats-version:
    name: my-first-job
    runs-on: ubuntu-latest
    steps:
    - name: First Powershell step
      shell: pwsh
      run: |
        Write-Host "Hello world! Hi!"
