name: Pester-tests
on: [pull_request]

jobs:
  cloudsmith-housekeeper-tests:
    name: Pester tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform a Pester test from the Unit.Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester Find-PackagesToDelete.Tests.ps1 -Passthru | Export-CliXml -Path Find-PackagesToDelete.Tests.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-Find-PackagesToDelete-Tests
          path: Find-PackagesToDelete.Tests.xml
    if: ${{ always() }}