name: Build and Deploy
on:
  push:
    branches:    
      - main
  workflow_dispatch:
    inputs:
      host:
        description: 'Host in Dev environment'
        required: true
        default: 'dev03' 
        type: choice
        options:
        - dev03
        - dev04
        - dev06
        - dev07

jobs:
  Tests:
    name: Test multiple triggers
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.host }}