name: workflow-name
on: pull_request

env:
  jobToRun: 'first-job'
  
jobs:
  job-id-1:
    name: job-name-1
    if: github.repository == 'ZsaniTestOrg/TestRepository'
    runs-on: ubuntu-latest
    steps:
    - name: First Powershell step
      shell: pwsh
      run: |
        Write-Host "Hello world!"
  job-id-2:
    name: job-name-2
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
    - name: First Powershell step
      shell: pwsh
      run: |
        Write-Host "Hi!"
