name: workflow-name
on: pull_request
jobs:
  job-id-1:
    name: job-name-1
    runs-on: ubuntu-latest
    steps:
    - name: First Powershell step
      shell: pwsh
      run: |
        Write-Host "Hello world! Hi!"
  job-id-2:
    name: job-name-2
    runs-on: ubuntu-latest
    steps:
    - name: First Powershell step
      shell: pwsh
      run: |
        Write-Host "Hello world! Hi!"
