name: learn-github-actions
on: pull_request
jobs:
  job-id:
    runs-on: ubuntu-latest
    steps:
    - name: First Powershell step
      shell: pwsh
      run: |
        Write-Host "Hello world! Hi!"
