name: learn-github-actions
on: [pull_request]

jobs:
  cloudsmith-housekeeper-tests:
    name: Pester tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: Test-Path README.md | Should -Be $true