name: learn-github-actions
on: [pull_request]

jobs:
  cloudsmith-housekeeper-tests:
    name: Pester tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform a Pester test from the Unit.Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester Unit.Tests.ps1 -Passthru