name: learn-github-actions
on: [pull_request]
jobs:
  check-bats-version:
    name: my-first-job
    runs-on: ubuntu-latest
    steps:
      - name: pester-tests-report
        uses: zyborg/pester-tests-report@v1.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
