name: workflow-name
on: pull_request

env:
  isFirstJob: true
  
jobs:
  job-id-1:
    if: isFirstJob == true
    runs-on: ubuntu-latest
    steps:
    - name: First Powershell step
      shell: pwsh
      run: |
        Write-Host "Hello world!"
  job-id-2:
    if: isFirstJob == false
    runs-on: ubuntu-latest
    steps:
    - name: First Powershell step
      shell: pwsh
      run: |
        Write-Host "Hi!"
