name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  backend_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: '[Backend] Release Drafter'
        uses: release-drafter/release-drafter@v5.23.0
        with:
          config-name: release-drafter-backend.yml
          disable-autolabeler: false
          disable-releaser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  frontend_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: '[Frontend] Release Drafter'
        uses: release-drafter/release-drafter@v5.23.0
        with:
          config-name: release-drafter-frontend.yml
          disable-autolabeler: false
          disable-releaser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
